[package]
name = "internet_info"
version = "0.1.0"
edition = "2021"

[dependencies]
isahc = "1.7.0"
crossbeam-channel = "0.5.4"
tui = "0.17.0"
crossterm = "0.22"
bincode = "1.3.3"
lazy_static = "1.4.0"
simple_config_parser = "1.0.0"
